{
  elementTypeClass="com.dreambox.csv.CsvElementType";

  tokens=[
    csvEol="regexp:[\r\n]+"
    csvEof='<<EOF>>'
    csvLiteral="regexp:[^,\r\n'\"][^,\r\n]*"
    csvString="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\")"
    csvComma=','
  ]


}

root ::= csvLine *
csvLine ::=  !<<eof>> csvValue (csvComma csvValue)* ( csvEol | <<eof>>)
csvValue ::= (csvString | csvLiteral)?

