{
  tokens=[
    eol="regexp:[\n\r]+"
    eof='<<EOF>>'
    literal="regexp:[^,\n'\"][^,\n]*"
    string="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\")"
    comma=','
  ]

}

root ::= line *
line ::=  !<<eof>> value (comma value)* ( eol | <<eof>>)
value ::= (string | literal)?

