{
 // elementTypeClass="com.dreambox.csv.CsvElementType";

  tokens=[
    eol="regexp:[\r\n]+"
    eof='<<EOF>>'
    literal="regexp:[^,\r\n'\"][^,\r\n]*"
    string="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\")"
    comma=','
  ]


}

root ::= csvLine *
csvLine ::=  !<<eof>> value (comma value)* ( eol | <<eof>>)
value ::= (string | literal)?

